### ISSUE TITLE
CSS Homework Review

### ISSUE THREAD

**Issue by manapard** [nbarbasina/evo-ts-bootcamp#2]
Привет 👋🏻 

Проверил твою домашку по CSS. Нашел только твой календарик, если ты делала галерею картинок, то скинь плиз здесь ссылку на нее.

- На широких экранах твой календарик разваливается и выглядит непрезентабельно.  Я бы тебе посоветовал ограничить размеры контейнера, например.
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/58340039/115682940-9c54f980-a35e-11eb-9c99-d6c525bd5a94.png">
- По коду у тебя есть такие вот стили
```css
.month {
  display: grid;
  grid-template-rows: 1fr;
  grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr 1fr;
}
```

Можно было бы упростить с помощью функции repeat()

```css
.month {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
}
```

Если ты уже прошла CSS Garden, то почитай пару статьей про CSS Grid, чтобы закрепить знания
- https://learncssgrid.com/#repeating-grid-tracks
- https://gridbyexample.com
